'use client';

import { useEffect, useRef, useState } from 'react';
import { Area, Task, Workspace, STORAGE_KEY, areas, day, initialWorkspace, isWorkspace } from '@/lib/organizer';

type IconName = 'sun'|'inbox'|'calendar'|'grid'|'check'|'plus'|'search'|'arrow'|'chevron'|'more'|'leaf'|'work'|'home'|'heart'|'flag'|'clock'|'close'|'download'|'settings'|'note'|'play'|'refresh';
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName,string> = {
    sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5',
    inbox:'M4 4h16l2 10v6H2v-6L4 4ZM2 14h6l2 3h4l2-3h6',calendar:'M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2ZM7 2v6m10-6v6M3 11h18m-13 4h2m4 0h2',grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',search:'M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15ZM16 16l5 5',arrow:'M4 12h16m-6-6 6 6-6 6',chevron:'m9 5 7 7-7 7',more:'M5 12h.01M12 12h.01M19 12h.01',leaf:'M20 3C8 2 1 8 6 16s16 2 14-13ZM4 21l12-13',work:'M3 7h18v13H3ZM8 7V3h8v4M3 12c5 3 13 3 18 0m-9 0v4',home:'m2 11 10-8 10 8M5 9v12h14V9m-10 12v-7h6v7',heart:'M12 21 3 12C-3 4 7-1 12 6c5-7 15-2 9 6Z',flag:'M5 22V3c5-5 9 5 15 0v11c-6 5-10-5-15 0',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 4v5l4 2',close:'m6 6 12 12M6 18 18 6',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',note:'M4 3h16v18H4ZM8 8h8M8 12h8M8 16h5',play:'m8 4 12 8-12 8Z',refresh:'M20 7A9 9 0 1 0 21 15M20 2v6h-6'
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
const areaIcons: Record<Area, IconName> = { Work: 'work', Personal: 'leaf', Health: 'heart', Home: 'home' };
const nav: {label:string; icon:IconName}[] = [{label:'Today',icon:'sun'},{label:'Inbox',icon:'inbox'},{label:'Upcoming',icon:'calendar'},{label:'All tasks',icon:'grid'},{label:'Completed',icon:'check'}];
const reviews = ['Empty your inbox. Give every thought a home.','Look back. Acknowledge what you finished.','Look ahead. Check what’s coming up.','Choose one thing that matters next week.'];
function Modal({ title, children, onClose }: {title:string;children:React.ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDivElement>(null);
  const closeRef=useRef(onClose);closeRef.current=onClose;
  useEffect(()=>{ const previous=document.activeElement as HTMLElement; const el=ref.current; el?.querySelector<HTMLElement>('input, textarea, button')?.focus();
    const handler=(e:KeyboardEvent)=>{if(e.key==='Escape') closeRef.current(); if(e.key==='Tab'&&el){const nodes=Array.from(el.querySelectorAll<HTMLElement>('button,input,select,textarea,[href]')).filter(n=>!n.hasAttribute('disabled'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><Icon name="close"/></button></div>{children}</div></div>;
}
export default function Organizer() {
  const [workspace,setWorkspace]=useState<Workspace|null>(null);
  const [view,setView]=useState('Today'); const [search,setSearch]=useState('');const [filter,setFilter]=useState('All');
  const [editor,setEditor]=useState<Task|null>(null);const [panel,setPanel]=useState<'review'|'settings'|null>(null);
  const [quick,setQuick]=useState(''); const [toast,setToast]=useState('');const [storageError,setStorageError]=useState('');
  const [focusId,setFocusId]=useState<string|null>(null);const [seconds,setSeconds]=useState(25*60);const [running,setRunning]=useState(false);
  const [today,setToday]=useState(day());const [menu,setMenu]=useState(false);const searchRef=useRef<HTMLInputElement>(null);const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){const parsed=JSON.parse(saved);if(!isWorkspace(parsed))throw new Error('Invalid data');setWorkspace(parsed);}else setWorkspace(initialWorkspace());}catch{setStorageError('Saved data could not be loaded. Export a backup before making changes.');setWorkspace(initialWorkspace());}},[]);
  useEffect(()=>{if(workspace&&!storageError){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(workspace));}catch{setStorageError('Your browser could not save changes. Export a backup to keep your work.');}}},[workspace,storageError]);
  useEffect(()=>{const timer=setInterval(()=>setToday(day()),60000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{if(!running)return;const end=Date.now()+seconds*1000;const timer=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(left);if(left===0){setRunning(false);setToast('Focus session complete. Take a breath and a short break.');}},250);return()=>clearInterval(timer);},[running,focusId]); // The deadline is set when a session starts or resumes.
  if(!workspace)return <div className="loading"><span className="brand-mark"><Icon name="sun" size={28}/></span> A little more clarity…</div>;
  const tasks=workspace.tasks;const doneToday=tasks.filter(t=>t.done&&(t.completedOn||t.date)===today).length;const todayTasks=tasks.filter(t=>t.date&&t.date<=today&&!t.done);const todayTotal=todayTasks.length+doneToday;
  const update=(patch:Partial<Workspace>)=>setWorkspace(w=>w?{...w,...patch}:w);
  const patchTask=(id:string,patch:Partial<Task>)=>setWorkspace(w=>w?{...w,tasks:w.tasks.map(t=>t.id===id?{...t,...patch}:t)}:w);
  const openNew=()=>setEditor({id:crypto.randomUUID(),title:'',area:areas.includes(view as Area)?view as Area:'Personal',date:view==='Today'?today:'',priority:'Normal',minutes:15,notes:'',done:false,focus:false});
  const changeView=(next:string)=>{setView(next);setFilter('All');setSearch('');setMenu(false);};
  const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`daylight-${today}.json`;a.click();URL.revokeObjectURL(url);setToast('Backup exported. Keep it somewhere safe.');};
  const focusTask=tasks.find(t=>t.id===focusId)||todayTasks.find(t=>t.focus)||todayTasks[0];
  const visible=tasks.filter(t=>search?`${t.title} ${t.notes} ${t.area}`.toLowerCase().includes(search.toLowerCase()):view==='Today'?!!t.date&&t.date<=today&&!t.done:view==='Inbox'?!t.date&&!t.done:view==='Upcoming'?t.date>today&&!t.done:view==='Completed'?t.done:areas.includes(view as Area)?t.area===view&&!t.done:!t.done).filter(t=>filter==='All'||(filter==='High priority'?t.priority==='High':t.minutes<=15)).sort((a,b)=>(view==='Upcoming'?a.date.localeCompare(b.date):0)||Number(b.focus)-Number(a.focus)||Number(b.priority==='High')-Number(a.priority==='High')||a.date.localeCompare(b.date));
  const greeting=new Date().getHours()<12?'Good morning':new Date().getHours()<17?'Good afternoon':'Good evening';
  const title=search?'Find your next thing':view==='Today'?`${greeting}, ${workspace.name}.`:view==='Inbox'?'A place for everything.':view==='Upcoming'?'A little perspective.':view==='Completed'?'Look how far you’ve come.':view==='All tasks'?'Everything, in one place.':`${view}, with intention.`;
  const subtitle=search?`Results for “${search}”`:view==='Today'?'You don’t have to do it all. Just the next right thing.':view==='Inbox'?'Get it out of your head. Decide where it belongs when you’re ready.':view==='Upcoming'?'See what’s ahead and make a little room for it.':view==='Completed'?'Small steps add up. Every one of these counts.':'Give your commitments a little space and structure.';
  const startFocus=()=>{if(!focusTask){openNew();return;}setFocusId(focusTask.id);if(seconds===0)setSeconds(1500);setRunning(r=>!r);};
  return <div className="app-shell">
    <aside className={`sidebar ${menu?'mobile-open':''}`}>
      <a className="brand" href="/" aria-label="Daylight home"><span className="brand-mark"><Icon name="sun" size={27}/></span>daylight<span className="brand-dot">.</span></a>
      <div className="workspace-label"><span className="workspace-avatar">C</span><div>Personal workspace<small>A little more clarity</small></div><span className="workspace-check"><Icon name="check" size={13}/></span></div>
      <button className="search-trigger" onClick={()=>{setMenu(false);searchRef.current?.focus();}}><Icon name="search" size={17}/> Search anything <kbd>⌘ K</kbd></button>
      <div className="nav-label">MY SPACE</div><nav aria-label="Main navigation">{nav.map(n=><button key={n.label} className={`nav-item ${view===n.label?'active':''}`} onClick={()=>changeView(n.label)}><Icon name={n.icon}/><span>{n.label}</span>{['Today','Inbox'].includes(n.label)&&<span className="nav-count">{n.label==='Today'?todayTasks.length:tasks.filter(t=>!t.date&&!t.done).length}</span>}</button>)}</nav>
      <div className="nav-label areas-label">LIFE AREAS <span>4</span></div><nav aria-label="Life areas">{areas.map(a=><button key={a} className={`nav-item ${view===a?'active':''}`} onClick={()=>changeView(a)}><span className={`area-dot ${a.toLowerCase()}`}/><span>{a}</span><span className="area-count">{tasks.filter(t=>t.area===a&&!t.done).length}</span></button>)}</nav>
      <button className="reset-card" onClick={()=>setPanel('review')}><span className="reset-icon"><Icon name="refresh" size={19}/></span><strong>A fresh start, every week</strong><p>Reflect, reset, and find your focus.</p><span>Start your weekly reset <Icon name="arrow" size={16}/></span></button>
      <div className="sidebar-bottom"><button className="profile" onClick={()=>setPanel('settings')}><span className="avatar">{workspace.name.slice(0,1).toUpperCase()}</span><span>{workspace.name}<small>Personal account</small></span><Icon name="settings" size={18}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-toggle" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Icon name="grid"/></button><span className="breadcrumb">My workspace <Icon name="chevron" size={13}/> <strong>{view}</strong></span><div className="topbar-right"><span className="saved-indicator"><i/>{storageError?'Save needs attention':'Saved on this device'}</span><button className="add-button" onClick={openNew}><Icon name="plus" size={17}/> Add task</button></div></header>
      <main>
        {storageError&&<div className="error-banner" role="alert">{storageError} <button onClick={exportData}>Export backup</button></div>}
        <div className="date-eyebrow"><Icon name="sun" size={16}/>{new Date(`${today}T12:00:00`).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</div>
        <div className="greeting"><div><h1>{title}</h1><p>{subtitle}</p></div><span className="greeting-flower" aria-hidden="true">✳</span></div>
        {view==='Today'&&!search&&<>
          <section className="focus-banner"><div className="focus-copy"><div className="eyebrow"><span className="tiny-spark">✧</span> A LITTLE INTENTION GOES A LONG WAY</div><input aria-label="Daily intention" className="intention-input" value={workspace.intention} onChange={e=>update({intention:e.target.value})}/><p>One clear priority. A few small steps. A day that feels like yours.</p><button className="focus-button" onClick={startFocus}><Icon name={running?'clock':'play'} size={15}/>{running?`Pause focus · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:focusId?'Resume focus session':'Let’s find your focus'}<Icon name="arrow" size={16}/></button></div><div className="landscape" aria-hidden="true"><div className="sun-orb"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hill hill-back"/><div className="hill hill-mid"/><div className="hill hill-front"/><div className="plant plant-one"/><div className="plant plant-two"/></div></section>
          <section className="stats" aria-label="Daily overview"><div><span className="stat-icon peach"><Icon name="sun"/></span><div><span className="stat-number">{todayTasks.length}<small>tasks for today</small></span><p>A manageable place to start</p></div></div><div><span className="stat-icon sage"><Icon name="check"/></span><div><span className="stat-number">{doneToday}<small>completed</small></span><p>Little wins, real progress</p></div></div><div><span className="stat-icon lavender"><Icon name="clock"/></span><div><span className="stat-number">{todayTasks.reduce((n,t)=>n+t.minutes,0)}<small>minutes planned</small></span><p>Leave some room to breathe</p></div></div></section>
        </>}
        <div className="content-grid"><div className="primary-content">
          <section className="task-section"><div className="section-heading"><h2>{search?'Search results':view==='Today'?'Your plan for today':view==='Inbox'?'Your inbox':view==='Upcoming'?'On the horizon':view==='Completed'?'Finished tasks':view==='All tasks'?'All your tasks':`${view} tasks`} <span>{visible.length}</span></h2><button className="text-button" onClick={openNew}><Icon name="plus" size={16}/> Add task</button></div>
            <div className="task-toolbar"><div className="filter-tabs">{['All','High priority','Quick wins'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="inline-search"><Icon name="search" size={16}/><input ref={searchRef} aria-label="Search tasks" placeholder="Search tasks" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="icon-button" aria-label="Clear search" onClick={()=>setSearch('')}><Icon name="close" size={13}/></button>}</div></div>
            <div className="task-list">{visible.length===0?<div className="empty-state"><span><Icon name={view==='Completed'?'check':'leaf'} size={27}/></span><h3>{search?'No matching tasks':view==='Today'?'A little breathing room.':'A clean slate.'}</h3><p>{search?'Try another word, or clear your search.':'Capture something on your mind, or enjoy the space.'}</p><button className="text-button" onClick={openNew}>Add a task <Icon name="plus" size={15}/></button></div>:visible.map(t=><div key={t.id} className={`task-row ${t.done?'done':''}`}><button className={`task-checkbox ${t.done?'checked':''}`} aria-label={`${t.done?'Reopen':'Complete'} ${t.title}`} onClick={()=>{patchTask(t.id,{done:!t.done,completedOn:!t.done?today:undefined});if(!t.done&&focusId===t.id){setRunning(false);setFocusId(null);setSeconds(1500);}setToast(t.done?'Task reopened.':'One less thing on your mind. Nicely done.');}}>{t.done&&<Icon name="check" size={13}/>}</button><button className="task-body" onClick={()=>setEditor({...t})}><span className="task-title">{t.title}</span><span className="task-meta"><span className={`area-tag ${t.area.toLowerCase()}`}>{t.area}</span><span><Icon name="clock" size={12}/>{t.minutes} min</span>{t.date&&t.date!==today&&<span className={t.date<today&&!t.done?'overdue':''}>{t.date<today&&!t.done?'Overdue · ':''}{new Date(`${t.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span>}{t.notes&&<Icon name="note" size={13}/>}</span></button>{t.focus&&<span className="focus-tag">✧ Focus</span>}<button className={`priority-button ${t.priority==='High'?'high':''}`} aria-label={`${t.priority==='High'?'Remove':'Set'} high priority for ${t.title}`} onClick={()=>patchTask(t.id,{priority:t.priority==='High'?'Normal':'High'})}><Icon name="flag" size={16}/></button><button className="icon-button row-more" aria-label={`Edit ${t.title}`} onClick={()=>setEditor({...t})}><Icon name="more" size={18}/></button></div>)}</div>
            <form className="quick-add" onSubmit={e=>{e.preventDefault();if(!quick.trim())return;const newTask:Task={id:crypto.randomUUID(),title:quick.trim(),area:areas.includes(view as Area)?view as Area:'Personal',date:view==='Today'?today:'',priority:'Normal',minutes:15,notes:'',done:false,focus:false};update({tasks:[...tasks,newTask]});setQuick('');setToast('Task captured. You can let that thought go.');}}><Icon name="plus" size={18}/><input aria-label="Quick add task" placeholder="Add a task. Get it off your mind…" value={quick} onChange={e=>setQuick(e.target.value)}/><button type="submit" aria-label="Save quick task">↵</button></form>
            {view==='Today'&&doneToday>0&&<button className="completed-link" onClick={()=>changeView('Completed')}><Icon name="check" size={16}/>{doneToday} completed today<span>Look at you go.</span><Icon name="chevron" size={13}/></button>}
          </section>
          <section className="areas-section"><div className="section-heading"><h2>A little balance</h2><span className="subtle">Your life, beyond a list</span></div><div className="area-cards">{areas.map(a=><button className={`area-card ${a.toLowerCase()}`} key={a} onClick={()=>changeView(a)}><span className="area-card-top"><span className="area-card-icon"><Icon name={areaIcons[a]} size={20}/></span><Icon name="arrow" size={15}/></span><strong>{a}</strong><span>{tasks.filter(t=>t.area===a&&!t.done).length} open tasks</span><div className="area-progress"><i style={{width:`${tasks.filter(t=>t.area===a).length?tasks.filter(t=>t.area===a&&t.done).length/tasks.filter(t=>t.area===a).length*100:0}%`}}/></div></button>)}</div></section>
        </div><aside className="right-rail">
          <section className="progress-card"><div className="section-heading"><h3>One step at a time</h3><Icon name="leaf" size={17}/></div><div className="progress-ring" style={{background:`conic-gradient(#657a58 ${todayTotal?doneToday/todayTotal*100:0}%, #eaece4 0)`}}><div><strong>{doneToday}<span>/{todayTotal}</span></strong><small>tasks complete</small></div></div><p>{todayTasks.length?'Progress is progress.':'Space for whatever comes next.'}<br/><strong>{doneToday?'You’re moving in the right direction.':'Start small. You’ve got this.'}</strong></p><div className="progress-foot"><span>Today’s momentum</span><span>{todayTotal?Math.round(doneToday/todayTotal*100):0}%</span></div><div className="linear-progress"><i style={{width:`${todayTotal?doneToday/todayTotal*100:0}%`}}/></div></section>
          <section className="notes-card"><div className="section-heading"><h3>A place for your thoughts</h3><Icon name="note" size={17}/></div><p>Catch it now. Make sense of it later.</p><textarea aria-label="Scratchpad" placeholder={'Something on your mind?\nAn idea, a reminder, a little note…'} value={workspace.note} onChange={e=>update({note:e.target.value})}/><div className="note-footer"><span>Just for you</span>{workspace.note&&<button className="text-button" onClick={()=>{setEditor({id:crypto.randomUUID(),title:workspace.note.split('\n')[0].slice(0,200),notes:workspace.note,area:'Personal',date:'',priority:'Normal',minutes:15,done:false,focus:false});}}>Turn into task <Icon name="arrow" size={13}/></button>}<span>↗</span></div></section>
          <div className="gentle-note"><span>✧</span><p>You’re a person, not a productivity machine. Leave a little room for life.</p></div>
        </aside></div>
        <footer className="page-footer"><span><span className="footer-sun">✳</span> A little less overwhelm. A little more you.</span>{workspace.sample&&<button onClick={()=>setPanel('settings')}>Example workspace <Icon name="arrow" size={13}/></button>}</footer>
      </main>
    </div>
    {focusId&&<div className="focus-session" role="status"><span className="focus-pulse"/><div><small>{seconds===0?'Session complete':running?'In your focus space':'Focus paused'}</small><strong>{focusTask?.title}</strong></div><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><button onClick={()=>{if(!seconds)setSeconds(1500);setRunning(!running);}}>{running?'Pause':seconds===0?'Restart':'Resume'}</button><button className="icon-button" aria-label="End focus session" onClick={()=>{setRunning(false);setFocusId(null);setSeconds(1500);}}><Icon name="close" size={16}/></button></div>}
    {toast&&<div className="toast" role="status"><Icon name="check" size={17}/>{toast}</div>}
    {editor&&<Modal title={tasks.some(t=>t.id===editor.id)?'Make a little space for this':'One less thing to keep in your head'} onClose={()=>setEditor(null)}><form onSubmit={e=>{e.preventDefault();if(!editor.title.trim())return;const saved={...editor,title:editor.title.trim()};update({tasks:tasks.some(t=>t.id===saved.id)?tasks.map(t=>t.id===saved.id?saved:t):[...tasks,saved]});setEditor(null);setToast('Task saved. A little more clarity.');}}><label>What needs your attention?<input required maxLength={200} value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Give it a clear next step"/></label><div className="form-grid"><label>Life area<select value={editor.area} onChange={e=>setEditor({...editor,area:e.target.value as Area})}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>When? <span>Blank = inbox</span><input type="date" value={editor.date} onChange={e=>setEditor({...editor,date:e.target.value})}/></label><label>Priority<select value={editor.priority} onChange={e=>setEditor({...editor,priority:e.target.value as Task['priority']})}><option>Normal</option><option>High</option></select></label><label>Time estimate (minutes)<input type="number" min="1" max="600" required value={editor.minutes} onChange={e=>setEditor({...editor,minutes:Number(e.target.value)})}/></label></div><label>A few details<textarea value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})} placeholder="Context, links, or the smallest first step…"/></label><label className="checkbox-label"><input type="checkbox" checked={editor.focus} onChange={e=>setEditor({...editor,focus:e.target.checked})}/> Make this a focus task</label><div className="modal-actions">{tasks.some(t=>t.id===editor.id)&&<button type="button" className="delete-button" onClick={()=>{update({tasks:tasks.filter(t=>t.id!==editor.id)});if(focusId===editor.id){setFocusId(null);setRunning(false);setSeconds(1500);}setEditor(null);setToast('Task removed.');}}>Delete task</button>}<button type="button" className="secondary-button" onClick={()=>setEditor(null)}>Cancel</button><button className="add-button" type="submit">Save task <Icon name="arrow" size={16}/></button></div></form></Modal>}
    {panel==='review'&&<Modal title="A fresh start, every week" onClose={()=>setPanel(null)}><p className="modal-intro">Take five quiet minutes. Clear the clutter, notice your progress, and choose what comes next.</p><div className="review-list">{reviews.map((r,i)=><label key={r}><input type="checkbox" checked={workspace.review.includes(r)} onChange={()=>update({review:workspace.review.includes(r)?workspace.review.filter(x=>x!==r):[...workspace.review,r]})}/><span><small>0{i+1}</small>{r}</span></label>)}</div><label>Your intention for the days ahead<input value={workspace.intention} onChange={e=>update({intention:e.target.value})}/></label><div className="modal-actions"><button className="secondary-button" onClick={()=>update({review:[]})}>Reset checklist</button><button className="add-button" onClick={()=>{setPanel(null);setToast(workspace.review.length===4?'Fresh perspective. You’re ready for a new week.':'Progress saved. Come back whenever you’re ready.');}}>Save & close <Icon name="check" size={16}/></button></div></Modal>}
    {panel==='settings'&&<Modal title="Make yourself at home" onClose={()=>setPanel(null)}><label>What should we call you?<input value={workspace.name} maxLength={30} onChange={e=>update({name:e.target.value})}/></label><div className="settings-section"><h3>Your space, on this device</h3><p>Tasks and notes are saved in this browser. Export a backup to keep a copy or move to another device. This workspace is separate from your existing InstantDB tasks.</p><div className="settings-buttons"><button className="secondary-button" onClick={exportData}><Icon name="download" size={16}/> Export backup</button><button className="secondary-button" onClick={()=>fileRef.current?.click()}>Restore backup</button><input type="file" accept="application/json,.json" ref={fileRef} hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const value=JSON.parse(await f.text());if(!isWorkspace(value))throw Error();if(window.confirm('Replace this local workspace with the selected backup?')){setWorkspace(value);setStorageError('');setFocusId(null);setRunning(false);setSeconds(1500);setToast('Your workspace has been restored.');}}catch{setToast('That file is not a valid Daylight backup.');}e.target.value='';}}/></div></div>{workspace.sample&&<div className="settings-section"><h3>Ready to make it yours?</h3><p>The starter tasks are examples. Clear them when you’re ready; any tasks you’ve added will stay.</p><button className="secondary-button" onClick={()=>{update({sample:false,tasks:tasks.filter(t=>!/^s[1-9]$/.test(t.id))});setFocusId(null);setRunning(false);setSeconds(1500);setToast('A fresh workspace, just for you.');}}>Clear example tasks</button></div>}<div className="modal-actions"><button className="add-button" onClick={()=>setPanel(null)}>Done <Icon name="check" size={16}/></button></div></Modal>}
  </div>;
}
