'use client';
import {useState} from 'react';
import {descendantIds,Step,toggleStep,WorkTask,WorkNote,Priority} from '@/lib/workroom';
import {Icon} from './WorkUI';
export default function TaskDetails({task,projects,notes,onChange,onClose,onDelete,onTimer,onNote}:{task:WorkTask;projects:string[];notes:WorkNote[];onChange:(patch:Partial<WorkTask>)=>void;onClose:()=>void;onDelete:()=>void;onTimer:()=>void;onNote:(id:string)=>void}){
  const [stepText,setStepText]=useState('');const [parent,setParent]=useState<string|null>(null);const [editing,setEditing]=useState<string|null>(null);
  const finished=task.steps.filter(s=>s.done).length;const source=notes.find(n=>n.id===task.noteId);
  const add=()=>{const lines=stepText.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)return;onChange({steps:[...task.steps,...lines.map(title=>({id:crypto.randomUUID(),title,done:false,parentId:parent}))]});setStepText('');setParent(null);};
  const renderSteps=(parentId:string|null,depth=0):React.ReactNode=>task.steps.filter(s=>s.parentId===parentId).map(s=><div className="step-branch" key={s.id}><div className={`step-line ${s.done?'is-done':''}`}><button className={`wr-check ${s.done?'checked':''}`} aria-label={`${s.done?'Uncheck':'Check'} ${s.title}`} onClick={()=>onChange({steps:toggleStep(task.steps,s.id)})}>{s.done&&<Icon name="check" size={12}/>}</button>{editing===s.id?<input aria-label="Edit checklist item" autoFocus value={s.title} onChange={e=>onChange({steps:task.steps.map(x=>x.id===s.id?{...x,title:e.target.value}:x)})} onBlur={()=>setEditing(null)} onKeyDown={e=>{if(e.key==='Enter')setEditing(null);}}/>:<button className="step-title" onClick={()=>setEditing(s.id)}>{s.title}</button>}<button className="wr-icon step-action" title="Add sub-item" aria-label={`Add sub-item to ${s.title}`} onClick={()=>{setParent(s.id);document.getElementById('step-input')?.focus();}}><Icon name="sub" size={14}/></button><button className="wr-icon step-action" aria-label={`Remove checklist item ${s.title}`} onClick={()=>{const ids=descendantIds(task.steps,s.id);onChange({steps:task.steps.filter(x=>!ids.has(x.id))});if(parent&&ids.has(parent))setParent(null);}}><Icon name="close" size={13}/></button></div>{renderSteps(s.id,depth+1)}</div>);
  return <aside className="task-details"><div className="detail-top"><span><Icon name="list" size={15}/> TASK DETAILS</span><button className="wr-icon" aria-label="Close task details" onClick={onClose}><Icon name="close" size={16}/></button></div><div className="detail-scroll"><div className="detail-badges"><span className={`priority-chip ${task.priority.toLowerCase()}`}><Icon name="flag" size={12}/>{task.priority} priority</span><span className="detail-id">{task.done?'Completed':'Open task'}</span></div><textarea className="detail-title" aria-label="Task title" rows={2} maxLength={300} value={task.title} onChange={e=>onChange({title:e.target.value})}/><button className={`complete-action ${task.done?'done':''}`} onClick={()=>onChange({done:!task.done,completedAt:task.done?'':new Date().toISOString(),...(!task.done?{steps:task.steps.map(s=>({...s,done:true}))}:{})})}><Icon name="check" size={15}/>{task.done?'Completed · Reopen task':'Mark complete'}</button>
    <div className="detail-fields"><label><span><Icon name="folder" size={15}/> Project</span><select value={task.project} onChange={e=>onChange({project:e.target.value})}>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label><span><Icon name="flag" size={15}/> Priority</span><select value={task.priority} onChange={e=>onChange({priority:e.target.value as Priority})}><option>High</option><option>Medium</option><option>Low</option></select></label><label><span><Icon name="calendar" size={15}/> Due date</span><input aria-label="Task due date" type="datetime-local" value={task.dueAt} onChange={e=>onChange({dueAt:e.target.value})}/></label><label><span><Icon name="bell" size={15}/> Reminder</span><input aria-label="Task reminder" type="datetime-local" value={task.remindAt} onChange={e=>onChange({remindAt:e.target.value,notifiedAt:''})}/></label><label><span><Icon name="clock" size={15}/> Estimate</span><div className="minute-input"><input aria-label="Task estimate in minutes" type="number" min={1} max={600} value={task.minutes} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=600)onChange({minutes:n});}}/> min</div></label></div>
    {task.remindAt&&<p className="reminder-hint"><span className="live-dot"/>{task.notifiedAt?'Reminder delivered. Change its time to schedule again.':'Reminder scheduled. Keep Workroom open to receive it.'}</p>}
    <div className="detail-section-title"><h3>Context & notes</h3><Icon name="note" size={15}/></div><textarea className="task-description" aria-label="Task context and notes" placeholder="What’s the outcome? Add context, links, or anything you’ll need later…" rows={3} value={task.body} onChange={e=>onChange({body:e.target.value})}/>
    {source&&<button className="source-link" onClick={()=>onNote(source.id)}><Icon name="link" size={14}/><span>From <strong>{source.title}</strong></span><Icon name="arrow" size={13}/></button>}
    <div className="detail-section-title"><h3>Checklist <span>{finished}/{task.steps.length}</span></h3><span>{task.steps.length?Math.round(finished/task.steps.length*100):0}%</span></div>{task.steps.length>0&&<div className="steps-progress"><i style={{width:`${finished/task.steps.length*100}%`}}/></div>}
    <div className="steps-tree">{renderSteps(null)}</div>{!task.steps.length&&<p className="checklist-empty">Break the work into small, checkable steps.</p>}{parent&&<div className="parent-label">Adding under: {task.steps.find(s=>s.id===parent)?.title}<button className="wr-icon" aria-label="Cancel nesting" onClick={()=>setParent(null)}><Icon name="close" size={12}/></button></div>}
    <form className="step-add" onSubmit={e=>{e.preventDefault();add();}}><Icon name="plus" size={15}/><input id="step-input" aria-label="New checklist item" value={stepText} onChange={e=>setStepText(e.target.value)} placeholder={parent?'Add a sub-item…':'Add a checklist item…'}/><button type="submit" aria-label="Save checklist item">↵</button></form>
  </div><div className="detail-footer"><button className="wr-icon delete-task" aria-label="Delete task" onClick={onDelete}><Icon name="trash" size={17}/></button><span>Changes save automatically</span><button className="wr-primary" disabled={task.done} onClick={onTimer}><Icon name="play" size={14}/> Focus</button></div></aside>;
}
